routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::resource('topics', 'TopicController');
Route::post('topics/{topic}/comments', 'CommentController@store');
Route::post('comments/{comment}/favorites', 'FavoriteController@store');
Route::delete('comments/{comment}', 'CommentController@destroy');


//Route::get('/home', 'HomeController@index')->name('home');

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\ModulesTraits\Favoriteable;
use App\Topic;

class Comment extends Model
{
    use Favoriteable;
    
    protected $guarded = [];
    protected $with = ['user', 'favorites'];
    
    public function path()
    {
        return '/comments/' . $this->id;
    }
    
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
    
    public function topic()
    {
        return $this->belongsTo(Topic::class, 'topic_id');
    }
    
}

app/Favorite.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Favorite extends Model
{
    protected $guarded = [];
    public $timestamps = false;
}

app/Topic.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Topic extends Model
{
    protected $guarded = [];
    protected $with = ['user'];
    
    protected static function boot()
    {
        parent::boot();
        
        static::addGlobalScope('commentsCount', function($builder){
            $builder->withCount('comments');
        });
        
        static::deleting(function($topic)
        {
            $topic->comments()->delete();
        });
    }
    
    public function path()
    {
        return '/topics/' . $this->id;
    }
    
    public function comments()
    {
        return $this->hasMany(Comment::class)->withCount('favorites');
    }
    
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
    
    public function addComment($comment)
    {
        $this->comments()->create($comment);
    }
    
    public function scopeFilter($builder, $filters)
    {
        return $filters->apply($builder);
    }        
    
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Topic;
use App\Comment;
use Illuminate\Support\Facades\Auth;

class CommentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function store(Topic $topic, Request $request)
    {
        $this->validate($request, [
            'body' => 'required'
        ]);
        
        $topic->addComment([
            'body' => request('body'),
            'user_id' => Auth::id()
        ]);
        
        return back();
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Topic  $comments
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $this->authorize('forceDelete', $comment);
        
        $comment->delete();
        if(request()->wantsJson())
            return response([], 204);
        
        return back();
    }
    
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FavoriteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Comment;

class FavoriteController extends Controller
{
    
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function store(Request $request, Comment $comment)
    {
        $comment->favorite(); 
        return back();
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TopicController.php
<?php

namespace App\Http\Controllers;

use App\Topic;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\User;
use App\Filters\TopicFilters;

class TopicController extends Controller
{
    
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(TopicFilters $topicFilters)
    {
        $topics = Topic::filter($topicFilters)->latest()->paginate(10);
        
        return view('topics.index', compact('topics'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('topics.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'body' => 'required'
        ]);
        
        $topic = Topic::create([
            'user_id' => Auth::id(),
            'title' => request('title'),
            'body' => request('body')
        ]);
        
        return redirect($topic->path());
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function show(Topic $topic)
    {
        $comments = $topic->comments()->latest()->paginate(10);
        return view('topics.show', compact('topic', 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function edit(Topic $topic)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Topic $topic)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function destroy(Topic $topic)
    {
        $this->authorize('forceDelete', $topic);
        
        $topic->delete();
        if(request()->wantsJson())
            return response([], 204);
        
        return redirect('/topics');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    Topics <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="/topics">
                                        All topics
                                    </a>
                                    
                                    @if(auth()->check())
                                    <a class="dropdown-item" href="/topics?username={{auth()->user()->name}}">
                                        My topics
                                    </a>
                                    @endif

                                    <a class="dropdown-item" href="/topics/create">
                                        Create a topic
                                    </a>
                                </div>
                            </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/topics/comments/comment.blade.php
<div class="panel panel-default">
 
    <div class="panel-body">
        <div class="level">
            <h5 class="flex">
                <a href="#">{{$comment->user->name}}</a> said {{$comment->created_at}}
            </h5>
 
            <div class="row">
                <form method="POST" action="/comments/{{$comment->id}}/favorites">
                    {{csrf_field()}}
                    <button type="submit" class="btn btn-dark {{$comment->isFavorited() ? 'disabled' : '' }}" {{$comment->isFavorited() ? 'disabled' : '' }}>
                        {{$comment->favorites_count}} {{str_plural('Favorite', $comment->favorites_count)}}
                    </button>
                </form>
                @can('forceDelete', $comment)
                    <form action="{{$comment->path()}}" method="POST">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <button class="btn btn-dark">Delete Comment</button>
                    </form>
                @endcan
            </div>
        </div>
    </div>
 
    <div class="panel-body">
        {{ $comment->body }}
    </div>
</div>

resources/views/topics/comments/form.blade.php
            @if(auth()->check())

                <form method="post" action="{{$topic->path()}} . /comments">
                    
                    <div class="form-group">
                        {{csrf_field()}}
                        
                        <textarea name="body" id="body" class="form-control" rows="3" required>
                        </textarea>
                        
                        <button type="submit" class="btn btn-dark">
                            Post a comment
                        </button>
                        
                    </div>
                    
                </form>

                @include('errors.form_errors')
            
            @else

            <p>
                
                Please <a href="{{route('login')}}">login</a> if u want to comment this topic
                
            </p>

            @endif

resources/views/topics/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    
    <div class="row">
        
        <div class="panel panel-default">
            
            <div class="panel-heading">
                
                Create a topic:
                
            </div>
            
            <div class="panel-body">
                
                <form method="post" action="/topics">
                    {{csrf_field()}}
                    
                    <div class="form-froup">
                        <label>
                            Title:
                        </label>
                        <input type="text" class="form-control" id="title" name="title" value="{{ old('title') }}" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="body">Body:</label>
                        <textarea name="body" id="body" class="form-control" rows="10" required>{{ old('body') }}</textarea>
                    </div>
                    
                    <button type="submit" class="btn btn-dark">
                        Post a topic
                    </button>
                    
                </form>
                
                @include('errors.form_errors')
                    
            </div>
            
        </div>
        
    </div>
    
</div>
@endsection

resources/views/topics/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    
    <div class="row">
        
        <div class="panel panel-default">
            
            <div class="panel-heading">
                
                Topics
                
            </div>
            
            <div class="panel-body">
                
                @foreach($topics as $topic)
                
                    <article>

                        <h4>
                            
                            <a href="/topics?username={{$topic->user->name}}">{{ $topic->user->name }}</a> posted:
                            
                            <a href="{{$topic->path()}}">{{$topic->title}}</a>
                            
                        </h4>
                        
                        <div class="body">
                            
                            <div>{{$topic->body}}</div>
                            
                            <div>Created at {{$topic->created_at}}</div>
                            
                            <div>Has {{$topic->comments_count}} {{ str_plural('comment', $topic->comments_count) }}</div>
                            
                        </div>
                        
                    </article>
                    
                @endforeach
                
                {{$topics->links()}}
                
            </div>
            
        </div>
        
    </div>
    
</div>
@endsection

resources/views/topics/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    
    <div class="row">
        
        <div class="panel panel-default">
            
            <div class="panel-heading">
                
                {{$topic->title}}
                
            </div>
            
            <div class="panel-body">

                <div>
                
                    {{$topic->body}}
                
                </div>
                    
            </div>
            
        </div>
        
    </div>
    
    <div class="row">
            
        <div class="panel panel-default">
         
            @foreach($comments as $comment)
                
                @include("topics.comments.comment")
                
            @endforeach
            
            {{$comments->links()}}
                
        </div>
            
    </div>
    
     <div class="row">
    
        <div class="panel panel-default">
            
            @include("topics.comments.form")
            
        </div>
    
    </div>
    
    @can('forceDelete', $topic)
        <form action="{{$topic->path()}}" method="POST">
            {{ csrf_field() }}
            {{ method_field('DELETE') }}
            <button class="btn btn-dark">Delete Topic</button>
        </form>
    @endcan
    
</div>
@endsection